# Generated by Django 5.0.4 on 2024-04-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="song_file",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
